PACKAGE_NAME="it87"
PACKAGE_VERSION="bc06d34.20260913"
MAKE[0]="make TARGET=${kernelver}"
BUILT_MODULE_NAME[0]="it87"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hwmon"
AUTOINSTALL="yes"
NO_WEAK_MODULES="yes"
